export * from "./landingpage";
export * from "./menupage";
export * from "./aboutUs";
export * from "./contactUs";
export * from "./orderPage";
export * from "./accountpage"
export * from "./shippingpage";
export * from "./orderHistorypage";
export * from "./dashboardpage";
